import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
const inter = Inter({ subsets: ["latin"] });
import NavBar from "./component/navbar";
import { CartProvider } from "./context/CartContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>

   
    <html lang="en">
      <body className="h-full bg-slate-200">
     
          <Header />
        <div className="flex px-32 bg-slate-200">
          {/* div 1 */}
          <div className="w-1/5 pt-4 mt-2 rounded-xl sticky">
            <NavBar />
          </div>

          {/* div 2 */}
          <div className="w-5/6 rounded-xl">
            {children}
          </div>

        </div>
        


      </body>
    </html>
    </CartProvider>
  );
}
