import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/header";
const inter = Inter({ subsets: ["latin"] });
import NavBar from "./component/navbar";
import { CartProvider } from "./context/CartContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartProvider>

   
    <html lang="en">
    <body className="h-full bg-slate-200">
  <Header />
  <div className="flex px-6   bg-slate-200">
    {/* div 1 */}
    <div className="w-full md:w-1/5 sm:hidden  lg:block pt-4 mt-2 rounded-xl sticky top-0">
      <NavBar />
    </div>

    {/* div 2 */}
    <div className="w-full md:w-full rounded-xl">
      {children}
    </div>
  </div>
</body>
    </html>
    </CartProvider>
  );
}
